name: docker_pull_ci

on:
  workflow_dispatch:
  pull_request:
    types: closed
    branches: main
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: hferreira/docker-pull-exporter:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
